obs_dim: ${obs_dim}
act_dim: ${act_dim}
T_cond: ${T_cond}
cond_embed_dim: 32
down_dims: [32, 128, 256]
device: ${device}
cond_mask_prob: ${cond_mask_prob}
weight_decay: 1e-6
cond_predict_scale: False
inpaint: ${policy.inpaint}
sampler_type: ${policy.sampler_type}
