obs_dim: ${obs_dim}
act_dim: ${act_dim}
d_model: 256
nhead: 4
num_layers: 4
T: ${T}
T_cond: ${T_cond}
cond_mask_prob: ${cond_mask_prob}
emb_dropout: 0.0
attn_dropout: 0.0
weight_decay: 1e-6
inpaint: ${policy.inpaint}
device: ${device}
